# -*- mode: ruby -*-
# vi: set ft=ruby :

# cloud-images.ubuntu.com

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  # config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network"
  # config.vm.synced_folder "./data", "/vagrant_data"

  # https://docs.docker.com/install/linux/docker-ce/ubuntu/
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end